apiVersion: v1
kind: Service
metadata:
  # The name of the Service
  name: nginx-service
spec:
  # This selector is crucial: It must match the labels of the pods you want to target.
  # Our deployment.yaml has 'app: nginx' in its template.
  selector:
    app: nginx
  
  ports:
    - protocol: TCP
      # The port that the Service will expose
      port: 80
      # The port on the pod/container that traffic will be sent to
      targetPort: 80

  # Determines how the Service is exposed. ClusterIP is the default.
  type: ClusterIP 
